global:
  scrape_interval: 2s #Scrape interval to every 2 seconds.
  evaluation_interval: 2s #Evaluate rules every 2 seconds.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "goexample"
    static_configs:
      - targets: ["goexample:8080"]
